package main

// initializeKPIData sets up initial KPI data based on provided document
func initializeKPIData() {
	// Initialize roles
	roles = []Role{
		{ID: 1, Name: "Admin Bank Supervisor", Description: "Supervises administrative banking operations"},
		{ID: 2, Name: "General Manager", Description: "Manages overall operations and facilities"},
		{ID: 3, Name: "Corporate Communication Supervisor", Description: "Handles corporate communications and social media"},
		{ID: 4, Name: "HRBP Supervisor", Description: "Human Resources Business Partner supervisor"},
		{ID: 5, Name: "HR Operations Supervisor", Description: "Supervises HR operations and payroll"},
		{ID: 6, Name: "IT Supervisor", Description: "Manages IT projects and infrastructure"},
	}

	// Initialize KPIs for Admin Bank Supervisor
	kpis = []KPI{
		// Admin Bank Supervisor - Quantitative KPIs
		{ID: 1, RoleID: 1, Category: "Quantitative",
			Name:        "Efisiensi Operasional - Pengolahan Dokumen",
			Description: "Efficiency in document processing",
			Metric:      "Waktu rata-rata proses dokumen (SP3K, berkas nasabah ke bank, dll.)",
			Unit:        "days",
			Target:      "Rata-rata waktu proses dokumen ≤ 2 hari kerja",
			TargetValue: 2,
			Operator:    "≤",
			Weight:      15},

		{ID: 2, RoleID: 1, Category: "Quantitative",
			Name:        "Efisiensi Operasional - Penyelesaian Permintaan Operasional",
			Description: "Efficiency in operational requests",
			Metric:      "Respon terhadap permintaan BI Checking, dll.",
			Unit:        "%",
			Target:      "95% selesai dalam SLA 2 hari kerja",
			TargetValue: 95,
			Operator:    "≥",
			Weight:      10},

		{ID: 3, RoleID: 1, Category: "Quantitative",
			Name:        "Ketepatan Waktu - Pengiriman Laporan",
			Description: "Timeliness of report submissions",
			Metric:      "Tepat waktu laporan proses bank dan lainnya",
			Unit:        "%",
			Target:      "100% laporan selesai tepat waktu",
			TargetValue: 100,
			Operator:    "=",
			Weight:      15},

		{ID: 4, RoleID: 1, Category: "Quantitative",
			Name:        "Ketepatan Waktu - Responsivitas",
			Description: "Responsiveness to internal requests",
			Metric:      "Waktu tanggapan terhadap permintaan internal (marketing, HR)",
			Unit:        "%",
			Target:      "90% permintaan ditanggapi dalam 1 hari kerja",
			TargetValue: 90,
			Operator:    "≥",
			Weight:      10},

		{ID: 5, RoleID: 1, Category: "Quantitative",
			Name:        "Akurasi dan Kualitas Data - Akurasi Data Entry",
			Description: "Accuracy of data entry",
			Metric:      "Kesalahan data pada proses entry",
			Unit:        "%",
			Target:      "Tingkat kesalahan ≤ 0,2%",
			TargetValue: 0.2,
			Operator:    "≤",
			Weight:      10},

		{ID: 6, RoleID: 1, Category: "Quantitative",
			Name:        "Akurasi dan Kualitas Data - Kesesuaian Kebijakan",
			Description: "Compliance with policies",
			Metric:      "Kepatuhan terhadap SOP dan kebijakan audit",
			Unit:        "%",
			Target:      "100% sesuai SOP dan kebijakan",
			TargetValue: 100,
			Operator:    "=",
			Weight:      10},

		{ID: 7, RoleID: 1, Category: "Quantitative",
			Name:        "Kepuasan Layanan Internal",
			Description: "Internal service satisfaction",
			Metric:      "Skor kepuasan dari tim marketing, HR, dan bank partner",
			Unit:        "%",
			Target:      "Skor kepuasan ≥ 90%",
			TargetValue: 90,
			Operator:    "≥",
			Weight:      10},

		{ID: 8, RoleID: 1, Category: "Quantitative",
			Name:        "Pengelolaan Arsip dan Dokumen - Ketersediaan Dokumen",
			Description: "Document availability",
			Metric:      "Kemudahan akses dokumen (soft copy dan hard copy)",
			Unit:        "%",
			Target:      "100% dokumen ditemukan dalam waktu < 5 menit",
			TargetValue: 100,
			Operator:    "=",
			Weight:      5},

		{ID: 9, RoleID: 1, Category: "Quantitative",
			Name:        "Pengelolaan Arsip dan Dokumen - Pengelolaan Arsip Aktif",
			Description: "Active archive management",
			Metric:      "Tingkat pembaruan data pada arsip",
			Unit:        "%",
			Target:      "95% arsip diperbarui dalam SLA",
			TargetValue: 95,
			Operator:    "≥",
			Weight:      5},

		{ID: 10, RoleID: 1, Category: "Quantitative",
			Name:        "Manajemen Tim - Kinerja Staf",
			Description: "Staff performance",
			Metric:      "Nilai kinerja Admin Bank Staff sesuai standar KPI",
			Unit:        "score",
			Target:      "Rating ≥ 7.5",
			TargetValue: 7.5,
			Operator:    "≥",
			Weight:      5},

		{ID: 11, RoleID: 1, Category: "Quantitative",
			Name:        "Manajemen Tim - Turnover Rate",
			Description: "Staff turnover rate",
			Metric:      "Persentase karyawan yang keluar dalam periode tertentu dibandingkan dengan rata-rata total karyawan",
			Unit:        "%",
			Target:      "≤ 20% per tahun",
			TargetValue: 20,
			Operator:    "≤",
			Weight:      5},

		// Admin Bank Supervisor - Qualitative KPIs
		{ID: 12, RoleID: 1, Category: "Qualitative",
			Name:        "Integrity",
			Description: "Personal and professional integrity",
			Metric:      "Integrity assessment",
			Unit:        "score",
			Target:      "High level of integrity",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      7.5}, // 25% of 30%

		{ID: 13, RoleID: 1, Category: "Qualitative",
			Name:        "Commitment",
			Description: "Commitment to job and organization",
			Metric:      "Commitment assessment",
			Unit:        "score",
			Target:      "High level of commitment",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      4.5}, // 15% of 30%

		{ID: 14, RoleID: 1, Category: "Qualitative",
			Name:        "Discipline",
			Description: "Work discipline",
			Metric:      "Discipline assessment",
			Unit:        "score",
			Target:      "High level of discipline",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      3}, // 10% of 30%

		{ID: 15, RoleID: 1, Category: "Qualitative",
			Name:        "Leadership",
			Description: "Leadership abilities",
			Metric:      "Leadership assessment",
			Unit:        "score",
			Target:      "Effective leadership",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      4.5}, // 15% of 30%

		{ID: 16, RoleID: 1, Category: "Qualitative",
			Name:        "Proactive",
			Description: "Proactive attitude",
			Metric:      "Proactiveness assessment",
			Unit:        "score",
			Target:      "High level of proactiveness",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      4.5}, // 15% of 30%

		{ID: 17, RoleID: 1, Category: "Qualitative",
			Name:        "Communication",
			Description: "Communication skills",
			Metric:      "Communication assessment",
			Unit:        "score",
			Target:      "Effective communication",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      3}, // 10% of 30%

		{ID: 18, RoleID: 1, Category: "Qualitative",
			Name:        "Innovation",
			Description: "Innovation and improvement",
			Metric:      "Innovation assessment",
			Unit:        "score",
			Target:      "High level of innovation",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      3}, // 10% of 30%

		// ===== GENERAL MANAGER KPIs =====
		// General Manager - Quantitative KPIs (70% weight)
		{ID: 19, RoleID: 2, Category: "Quantitative",
			Name:        "Pengelolaan Fasilitas - Tingkat Ketersediaan Fasilitas",
			Description: "Facility management - Availability",
			Metric:      "Persentase fasilitas operasional yang tersedia",
			Unit:        "%",
			Target:      "100% tersedia",
			TargetValue: 100,
			Operator:    "=",
			Weight:      15},

		{ID: 20, RoleID: 2, Category: "Quantitative",
			Name:        "Efisiensi Operasional - Kepatuhan terhadap Anggaran",
			Description: "Operational efficiency - Budget compliance",
			Metric:      "Persentase realisasi pengeluaran dibandingkan dengan anggaran yang ditetapkan",
			Unit:        "%",
			Target:      "Dalam rentang 95%-105% dari anggaran",
			TargetValue: 100, // Center of the range
			Operator:    "=",
			Weight:      20},

		{ID: 21, RoleID: 2, Category: "Quantitative",
			Name:        "Kepatuhan dan Regulasi - Kepatuhan pada Regulasi Internal",
			Description: "Compliance with internal regulations",
			Metric:      "Audit internal tanpa temuan pelanggaran",
			Unit:        "%",
			Target:      "100% patuh",
			TargetValue: 100,
			Operator:    "=",
			Weight:      10},

		{ID: 22, RoleID: 2, Category: "Quantitative",
			Name:        "Kepatuhan dan Regulasi - Kepatuhan Laporan Internal",
			Description: "Compliance with internal reporting",
			Metric:      "Ketepatan Waktu Laporan Internal",
			Unit:        "%",
			Target:      "100% sesuai jadwal",
			TargetValue: 100,
			Operator:    "=",
			Weight:      10},

		{ID: 23, RoleID: 2, Category: "Quantitative",
			Name:        "Pengelolaan Tim - Turnover Rate",
			Description: "Team management - Turnover rate",
			Metric:      "Persentase karyawan yang keluar dalam periode tertentu dibandingkan dengan rata-rata total karyawan",
			Unit:        "%",
			Target:      "≤ 20% per tahun",
			TargetValue: 20,
			Operator:    "≤",
			Weight:      10},

		{ID: 24, RoleID: 2, Category: "Quantitative",
			Name:        "Pengelolaan Tim - Jumlah Pelatihan Operasional",
			Description: "Team management - Operational training",
			Metric:      "Jumlah pelatihan operasional yang diadakan",
			Unit:        "count",
			Target:      "≥3 pelatihan per tahun",
			TargetValue: 3,
			Operator:    "≥",
			Weight:      10},

		{ID: 25, RoleID: 2, Category: "Quantitative",
			Name:        "Inovasi dan Pengembangan - Program Baru",
			Description: "Innovation and development - New programs",
			Metric:      "Jumlah inisiatif atau program baru yang diterapkan",
			Unit:        "count",
			Target:      "≥2 program per tahun",
			TargetValue: 2,
			Operator:    "≥",
			Weight:      10},

		{ID: 26, RoleID: 2, Category: "Quantitative",
			Name:        "Engagement Karyawan - Tingkat Keterlibatan Karyawan",
			Description: "Employee engagement level",
			Metric:      "Rata rata engagement Karyawan",
			Unit:        "%",
			Target:      "Rata-rata ≥85% engagement",
			TargetValue: 85,
			Operator:    "≥",
			Weight:      5},

		// General Manager - Qualitative KPIs (30% weight)
		{ID: 27, RoleID: 2, Category: "Qualitative",
			Name:        "Integrity",
			Description: "Personal and professional integrity",
			Metric:      "Integrity assessment",
			Unit:        "score",
			Target:      "High level of integrity",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      7.5}, // 25% of 30%

		{ID: 28, RoleID: 2, Category: "Qualitative",
			Name:        "Commitment",
			Description: "Commitment to job and organization",
			Metric:      "Commitment assessment",
			Unit:        "score",
			Target:      "High level of commitment",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      4.5}, // 15% of 30%

		{ID: 29, RoleID: 2, Category: "Qualitative",
			Name:        "Discipline",
			Description: "Work discipline",
			Metric:      "Discipline assessment",
			Unit:        "score",
			Target:      "High level of discipline",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      3}, // 10% of 30%

		{ID: 30, RoleID: 2, Category: "Qualitative",
			Name:        "Leadership",
			Description: "Leadership abilities",
			Metric:      "Leadership assessment",
			Unit:        "score",
			Target:      "Effective leadership",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      4.5}, // 15% of 30%

		{ID: 31, RoleID: 2, Category: "Qualitative",
			Name:        "Proactive",
			Description: "Proactive attitude",
			Metric:      "Proactiveness assessment",
			Unit:        "score",
			Target:      "High level of proactiveness",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      4.5}, // 15% of 30%

		{ID: 32, RoleID: 2, Category: "Qualitative",
			Name:        "Communication",
			Description: "Communication skills",
			Metric:      "Communication assessment",
			Unit:        "score",
			Target:      "Effective communication",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      3}, // 10% of 30%

		{ID: 33, RoleID: 2, Category: "Qualitative",
			Name:        "Innovation",
			Description: "Innovation and improvement",
			Metric:      "Innovation assessment",
			Unit:        "score",
			Target:      "High level of innovation",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      3}, // 10% of 30%

		// ===== CORPORATE COMMUNICATION SUPERVISOR KPIs =====
		// Corporate Communication Supervisor - Quantitative KPIs (70% weight)
		{ID: 34, RoleID: 3, Category: "Quantitative",
			Name:        "Target Jumlah Follower",
			Description: "Social media follower target",
			Metric:      "Total follower count across platforms",
			Unit:        "count",
			Target:      "50.000 Annually",
			TargetValue: 50000,
			Operator:    "≥",
			Weight:      20},

		{ID: 35, RoleID: 3, Category: "Quantitative",
			Name:        "Social Media Engagement Rate",
			Description: "Social media interaction rate",
			Metric:      "Rata Rata Account engaged",
			Unit:        "%",
			Target:      "80% dari Interaction Monthly",
			TargetValue: 80,
			Operator:    "≥",
			Weight:      25},

		{ID: 36, RoleID: 3, Category: "Quantitative",
			Name:        "Non-Followers Engagement",
			Description: "Engagement with non-followers",
			Metric:      "Rata rata non-followers engagement",
			Unit:        "count",
			Target:      "2500 Non-Followers Monthly",
			TargetValue: 2500,
			Operator:    "≥",
			Weight:      25},

		{ID: 37, RoleID: 3, Category: "Quantitative",
			Name:        "Corporate Events",
			Description: "Corporate events organization",
			Metric:      "Number of corporate events held",
			Unit:        "count",
			Target:      "4 Annually",
			TargetValue: 4,
			Operator:    "≥",
			Weight:      15},

		{ID: 38, RoleID: 3, Category: "Quantitative",
			Name:        "Billboard Content",
			Description: "Billboard advertisement content",
			Metric:      "Number of billboard content created",
			Unit:        "count",
			Target:      "10 Annually",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      5},

		{ID: 39, RoleID: 3, Category: "Quantitative",
			Name:        "Website Traffic",
			Description: "Website visitor traffic",
			Metric:      "Number of website visitors",
			Unit:        "count",
			Target:      "7.000 Visitor Annually",
			TargetValue: 7000,
			Operator:    "≥",
			Weight:      10},

		// Corporate Communication Supervisor - Qualitative KPIs (30% weight)
		{ID: 40, RoleID: 3, Category: "Qualitative",
			Name:        "Integrity",
			Description: "Personal and professional integrity",
			Metric:      "Integrity assessment",
			Unit:        "score",
			Target:      "High level of integrity",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      7.5}, // 25% of 30%

		{ID: 41, RoleID: 3, Category: "Qualitative",
			Name:        "Commitment",
			Description: "Commitment to job and organization",
			Metric:      "Commitment assessment",
			Unit:        "score",
			Target:      "High level of commitment",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      4.5}, // 15% of 30%

		{ID: 42, RoleID: 3, Category: "Qualitative",
			Name:        "Discipline",
			Description: "Work discipline",
			Metric:      "Discipline assessment",
			Unit:        "score",
			Target:      "High level of discipline",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      3}, // 10% of 30%

		{ID: 43, RoleID: 3, Category: "Qualitative",
			Name:        "Leadership",
			Description: "Leadership abilities",
			Metric:      "Leadership assessment",
			Unit:        "score",
			Target:      "Effective leadership",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      4.5}, // 15% of 30%

		{ID: 44, RoleID: 3, Category: "Qualitative",
			Name:        "Proactive",
			Description: "Proactive attitude",
			Metric:      "Proactiveness assessment",
			Unit:        "score",
			Target:      "High level of proactiveness",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      4.5}, // 15% of 30%

		{ID: 45, RoleID: 3, Category: "Qualitative",
			Name:        "Communication",
			Description: "Communication skills",
			Metric:      "Communication assessment",
			Unit:        "score",
			Target:      "Effective communication",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      3}, // 10% of 30%

		{ID: 46, RoleID: 3, Category: "Qualitative",
			Name:        "Innovation",
			Description: "Innovation and improvement",
			Metric:      "Innovation assessment",
			Unit:        "score",
			Target:      "High level of innovation",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      3}, // 10% of 30%

		// ===== HRBP SUPERVISOR KPIs =====
		// HRBP Supervisor - Quantitative KPIs (70% weight)
		{ID: 47, RoleID: 4, Category: "Quantitative",
			Name:        "Rekrutmen dan Perekrutan - Waktu untuk Merekrut",
			Description: "Recruitment efficiency",
			Metric:      "Rata-rata waktu yang dibutuhkan untuk mengisi posisi terbuka",
			Unit:        "days",
			Target:      "≤ 30 hari per peran",
			TargetValue: 30,
			Operator:    "≤",
			Weight:      25},

		{ID: 48, RoleID: 4, Category: "Quantitative",
			Name:        "Retensi Karyawan - Tingkat Retensi",
			Description: "Employee retention rate",
			Metric:      "Persentase karyawan yang bertahan di perusahaan lebih dari 1 tahun (hanya yang mengundurkan diri secara pribadi, bukan atas usulan perusahaan)",
			Unit:        "%",
			Target:      "≥ 20% per tahun",
			TargetValue: 20,
			Operator:    "≥",
			Weight:      20},

		{ID: 49, RoleID: 4, Category: "Quantitative",
			Name:        "Retensi Karyawan - Tindak Lanjut Turnover",
			Description: "Turnover follow-up rate",
			Metric:      "Persentase karyawan yang keluar dan menyelesaikan exit interview",
			Unit:        "%",
			Target:      "≥ 80%",
			TargetValue: 80,
			Operator:    "≥",
			Weight:      10},

		{ID: 50, RoleID: 4, Category: "Quantitative",
			Name:        "Kepatuhan Tugas - Kepatuhan Dasar",
			Description: "Basic compliance with regulations",
			Metric:      "Kepatuhan terhadap kontrak dan hukum ketenagakerjaan",
			Unit:        "%",
			Target:      "100% kepatuhan",
			TargetValue: 100,
			Operator:    "=",
			Weight:      15},

		{ID: 51, RoleID: 4, Category: "Quantitative",
			Name:        "Pelatihan dan Pengembangan - Sesi Pelatihan",
			Description: "Training session frequency",
			Metric:      "Jumlah sesi pelatihan yang dilakukan setiap tahun",
			Unit:        "count",
			Target:      "≥ 2 sesi per tahun",
			TargetValue: 2,
			Operator:    "≥",
			Weight:      15},

		{ID: 52, RoleID: 4, Category: "Quantitative",
			Name:        "Pelatihan dan Pengembangan - Cakupan Pelatihan",
			Description: "Training coverage",
			Metric:      "Persentase karyawan yang mendapatkan pelatihan",
			Unit:        "%",
			Target:      "≥ 80% per tahun",
			TargetValue: 80,
			Operator:    "≥",
			Weight:      15},

		// HRBP Supervisor - Qualitative KPIs (30% weight)
		{ID: 53, RoleID: 4, Category: "Qualitative",
			Name:        "Integrity",
			Description: "Personal and professional integrity",
			Metric:      "Integrity assessment",
			Unit:        "score",
			Target:      "High level of integrity",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      7.5}, // 25% of 30%

		{ID: 54, RoleID: 4, Category: "Qualitative",
			Name:        "Commitment",
			Description: "Commitment to job and organization",
			Metric:      "Commitment assessment",
			Unit:        "score",
			Target:      "High level of commitment",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      4.5}, // 15% of 30%

		{ID: 55, RoleID: 4, Category: "Qualitative",
			Name:        "Discipline",
			Description: "Work discipline",
			Metric:      "Discipline assessment",
			Unit:        "score",
			Target:      "High level of discipline",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      3}, // 10% of 30%

		{ID: 56, RoleID: 4, Category: "Qualitative",
			Name:        "Leadership",
			Description: "Leadership abilities",
			Metric:      "Leadership assessment",
			Unit:        "score",
			Target:      "Effective leadership",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      4.5}, // 15% of 30%

		{ID: 57, RoleID: 4, Category: "Qualitative",
			Name:        "Proactive",
			Description: "Proactive attitude",
			Metric:      "Proactiveness assessment",
			Unit:        "score",
			Target:      "High level of proactiveness",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      4.5}, // 15% of 30%

		{ID: 58, RoleID: 4, Category: "Qualitative",
			Name:        "Communication",
			Description: "Communication skills",
			Metric:      "Communication assessment",
			Unit:        "score",
			Target:      "Effective communication",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      3}, // 10% of 30%

		{ID: 59, RoleID: 4, Category: "Qualitative",
			Name:        "Innovation",
			Description: "Innovation and improvement",
			Metric:      "Innovation assessment",
			Unit:        "score",
			Target:      "High level of innovation",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      3}, // 10% of 30%

		// ===== HR OPERATIONS SUPERVISOR KPIs =====
		// HR Operations Supervisor - Quantitative KPIs (70% weight)
		{ID: 60, RoleID: 5, Category: "Quantitative",
			Name:        "Akurasi Data - Akurasi Penggajian",
			Description: "Payroll accuracy",
			Metric:      "Persentase penggajian (data dan waktu) yang diproses tanpa kesalahan",
			Unit:        "%",
			Target:      "100%",
			TargetValue: 100,
			Operator:    "=",
			Weight:      25},

		{ID: 61, RoleID: 5, Category: "Quantitative",
			Name:        "Akurasi Data - Akurasi Data Karyawan",
			Description: "Employee data accuracy",
			Metric:      "Persentase data karyawan yang dimasukkan tanpa kesalahan",
			Unit:        "%",
			Target:      "≥ 95%",
			TargetValue: 95,
			Operator:    "≥",
			Weight:      15},

		{ID: 62, RoleID: 5, Category: "Quantitative",
			Name:        "Kepatuhan - Tugas Kepatuhan Dasar",
			Description: "Basic compliance tasks",
			Metric:      "Kepatuhan terhadap kontrak dan hukum ketenagakerjaan",
			Unit:        "%",
			Target:      "100% kepatuhan",
			TargetValue: 100,
			Operator:    "=",
			Weight:      15},

		{ID: 63, RoleID: 5, Category: "Quantitative",
			Name:        "Rekrutmen dan Perekrutan - Waktu Pemrosesan Kontrak",
			Description: "Contract processing time",
			Metric:      "Rata-rata waktu yang dibutuhkan untuk memproses kontrak karyawan baru",
			Unit:        "days",
			Target:      "≤ 5 hari setelah tanggal bergabung",
			TargetValue: 5,
			Operator:    "≤",
			Weight:      15},

		{ID: 64, RoleID: 5, Category: "Quantitative",
			Name:        "Pemanfaatan Teknologi - Pembaruan dan Pemeliharaan Data",
			Description: "Technology utilization for data maintenance",
			Metric:      "Persentase data yang tersimpan dalam HRIS atau sistem terintegrasi",
			Unit:        "%",
			Target:      "100%",
			TargetValue: 100,
			Operator:    "=",
			Weight:      20},

		{ID: 65, RoleID: 5, Category: "Quantitative",
			Name:        "Event - Event yang Diselenggarakan",
			Description: "Employee events organization",
			Metric:      "Jumlah event yang diadakan untuk karyawan setiap tahun",
			Unit:        "count",
			Target:      "≥ 3 event per tahun",
			TargetValue: 3,
			Operator:    "≥",
			Weight:      10},

		// HR Operations Supervisor - Qualitative KPIs (30% weight)
		{ID: 66, RoleID: 5, Category: "Qualitative",
			Name:        "Integrity",
			Description: "Personal and professional integrity",
			Metric:      "Integrity assessment",
			Unit:        "score",
			Target:      "High level of integrity",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      7.5}, // 25% of 30%

		{ID: 67, RoleID: 5, Category: "Qualitative",
			Name:        "Commitment",
			Description: "Commitment to job and organization",
			Metric:      "Commitment assessment",
			Unit:        "score",
			Target:      "High level of commitment",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      4.5}, // 15% of 30%

		{ID: 68, RoleID: 5, Category: "Qualitative",
			Name:        "Discipline",
			Description: "Work discipline",
			Metric:      "Discipline assessment",
			Unit:        "score",
			Target:      "High level of discipline",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      3}, // 10% of 30%

		{ID: 69, RoleID: 5, Category: "Qualitative",
			Name:        "Leadership",
			Description: "Leadership abilities",
			Metric:      "Leadership assessment",
			Unit:        "score",
			Target:      "Effective leadership",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      4.5}, // 15% of 30%

		{ID: 70, RoleID: 5, Category: "Qualitative",
			Name:        "Proactive",
			Description: "Proactive attitude",
			Metric:      "Proactiveness assessment",
			Unit:        "score",
			Target:      "High level of proactiveness",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      4.5}, // 15% of 30%

		{ID: 71, RoleID: 5, Category: "Qualitative",
			Name:        "Communication",
			Description: "Communication skills",
			Metric:      "Communication assessment",
			Unit:        "score",
			Target:      "Effective communication",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      3}, // 10% of 30%

		{ID: 72, RoleID: 5, Category: "Qualitative",
			Name:        "Innovation",
			Description: "Innovation and improvement",
			Metric:      "Innovation assessment",
			Unit:        "score",
			Target:      "High level of innovation",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      3}, // 10% of 30%

		// ===== IT SUPERVISOR KPIs =====
		// IT Supervisor - Quantitative KPIs (70% weight)
		{ID: 80, RoleID: 6, Category: "Quantitative",
			Name:        "Project - Project Delivery",
			Description: "Project delivery",
			Metric:      "Penyelesaian proyek IT sesuai timeline",
			Unit:        "%",
			Target:      "≥ 85%",
			TargetValue: 85,
			Operator:    "≥",
			Weight:      30},

		{ID: 81, RoleID: 6, Category: "Quantitative",
			Name:        "Pengawasan Insiden - Waktu Respon terhadap Insiden Kritis",
			Description: "Incident monitoring - Critical incident response time",
			Metric:      "Rata-rata waktu respon terhadap insiden IT yang kritis",
			Unit:        "hours",
			Target:      "≤ 1 jam",
			TargetValue: 1,
			Operator:    "≤",
			Weight:      20},

		{ID: 82, RoleID: 6, Category: "Quantitative",
			Name:        "Keselarasan Strategis - Pencapaian Target",
			Description: "Strategic alignment - Target achievement",
			Metric:      "Pencapaian Milestone implementasi strategi IT",
			Unit:        "%",
			Target:      "100%",
			TargetValue: 100,
			Operator:    "=",
			Weight:      20},

		{ID: 83, RoleID: 6, Category: "Quantitative",
			Name:        "Manajemen Tim - Kinerja Staf",
			Description: "Team management - Staff performance",
			Metric:      "Nilai kinerja IT Staff dan IT Support sesuai standar KPI",
			Unit:        "score",
			Target:      "Rating ≥ 7.5",
			TargetValue: 7.5,
			Operator:    "≥",
			Weight:      20},

		{ID: 84, RoleID: 6, Category: "Quantitative",
			Name:        "Manajemen Tim - Turnover Rate",
			Description: "Team management - Staff turnover rate",
			Metric:      "Persentase karyawan yang keluar dalam periode tertentu dibandingkan dengan rata-rata total karyawan",
			Unit:        "%",
			Target:      "≤ 20% per tahun",
			TargetValue: 20,
			Operator:    "≤",
			Weight:      10},

		// IT Supervisor - Qualitative KPIs (30% weight)
		{ID: 85, RoleID: 6, Category: "Qualitative",
			Name:        "Integrity",
			Description: "Personal and professional integrity",
			Metric:      "Integrity assessment",
			Unit:        "score",
			Target:      "High level of integrity",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      7.5}, // 25% of 30%

		{ID: 86, RoleID: 6, Category: "Qualitative",
			Name:        "Commitment",
			Description: "Commitment to job and organization",
			Metric:      "Commitment assessment",
			Unit:        "score",
			Target:      "High level of commitment",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      4.5}, // 15% of 30%

		{ID: 87, RoleID: 6, Category: "Qualitative",
			Name:        "Discipline",
			Description: "Work discipline",
			Metric:      "Discipline assessment",
			Unit:        "score",
			Target:      "High level of discipline",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      3}, // 10% of 30%

		{ID: 88, RoleID: 6, Category: "Qualitative",
			Name:        "Leadership",
			Description: "Leadership abilities",
			Metric:      "Leadership assessment",
			Unit:        "score",
			Target:      "Effective leadership",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      4.5}, // 15% of 30%

		{ID: 89, RoleID: 6, Category: "Qualitative",
			Name:        "Proactive",
			Description: "Proactive attitude",
			Metric:      "Proactiveness assessment",
			Unit:        "score",
			Target:      "High level of proactiveness",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      4.5}, // 15% of 30%

		{ID: 90, RoleID: 6, Category: "Qualitative",
			Name:        "Communication",
			Description: "Communication skills",
			Metric:      "Communication assessment",
			Unit:        "score",
			Target:      "Effective communication",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      3}, // 10% of 30%

		{ID: 91, RoleID: 6, Category: "Qualitative",
			Name:        "Innovation",
			Description: "Innovation and improvement",
			Metric:      "Innovation assessment",
			Unit:        "score",
			Target:      "High level of innovation",
			TargetValue: 10,
			Operator:    "≥",
			Weight:      3}, // 10% of 30%
	}

	// Save the initial data to Excel right away
	saveToExcel()
}
